# Generated by Django 3.1.7 on 2021-03-22 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='content',
            field=models.FileField(blank=True, upload_to='media/', verbose_name='Contenido'),
        ),
    ]
