# Generated by Django 3.1.7 on 2021-03-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210322_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='content',
            field=models.FileField(blank=True, upload_to='', verbose_name='Contenido'),
        ),
    ]
