# Generated by Django 3.1.7 on 2021-03-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210322_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='content',
            field=models.FileField(blank=True, upload_to='local/', verbose_name='Contenido'),
        ),
    ]
