# Generated by Django 3.1.7 on 2021-03-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210322_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='local',
            field=models.BooleanField(default=True, verbose_name='Archivo Local'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
