# Generated by Django 3.1.7 on 2021-03-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210322_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Descripcion'),
        ),
    ]
