# Generated by Django 3.1.7 on 2021-03-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210325_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='share_link',
            field=models.CharField(blank=True, max_length=200, verbose_name='Compartir'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, verbose_name='Contenido'),
        ),
    ]
