# Generated by Django 3.1.7 on 2021-03-25 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210325_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='item_type',
            field=models.CharField(choices=[('Texto', 'Texto'), ('Media', 'Media')], default='Texto', max_length=50, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='section',
            name='media',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='texto',
            field=models.TextField(default=0, verbose_name='Texto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='section',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.post'),
        ),
    ]
